name: xCommands
description: xNetwork | Plugin odpowiadajacy za komendy
main: me.nexciak.xcommands.Main
version: 1.0
commands:
  kill:
    aliases: zabij
  gm:
    aliases: gamemode
  difficulty:
    aliases: dif
  msg:  
permissions:
    xcommands.*:
        default: op
        children:
            xcommands.kill: true
            xcommands.gm: true
            xcommands.difficulty: true
            xcommands.msg: true            
    xcommands.kill:
      default: op
    xcommands.gm:
      default: op
    xcommands.difficulty:
      default: op
    xcommands.msg:
      default: op
